# Generated by Django 5.0.6 on 2024-05-30 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('availability', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('likes_count', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('artwork_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
