# Generated by Django 5.0.6 on 2024-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_artwork_id_artwork__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
