# Generated by Django 5.0.6 on 2024-06-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_artwork_likes_count_alter_artwork_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='likes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
