# Generated by Django 5.0.6 on 2024-06-16 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_liked_by_alter_review_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='artwork',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
