# Generated by Django 5.0.6 on 2024-06-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_artwork_likes_count_artwork_liked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='liked_by',
        ),
    ]
