# Generated by Django 5.0.6 on 2024-06-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_deliveryaddress_delete_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='orderDate',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_price',
            new_name='shippingPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tax_price',
            new_name='taxPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='totalPrice',
        ),
    ]
