# Generated by Django 5.0.6 on 2024-06-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_order_date_order_orderdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='delivery_price',
            new_name='deliveryPrice',
        ),
    ]
