# Generated by Django 5.0.6 on 2024-06-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_delivery_price_deliveryaddress_deliveryprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='deliveryPrice',
        ),
    ]
