# Generated by Django 5.0.6 on 2024-06-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_shippingprice_order_deliveryprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isDelivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderDate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paidAt',
        ),
    ]
