# Generated by Django 5.0.6 on 2024-06-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_order_id_order__id_alter_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
