# Generated by Django 5.0.6 on 2024-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_deliveryaddress_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='postalCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
