# Generated by Django 5.0.6 on 2024-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_deliveryaddress_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.webp', null=True, upload_to=''),
        ),
    ]
