export const ARTWORK_LIST_REQUEST = 'ARTWORK_LIST_REQUEST'
export const ARTWORK_LIST_SUCCESS = 'ARTWORK_LIST_SUCCESS'
export const ARTWORK_LIST_FAIL = 'ARTWORK_LIST_FAIL'

export const ARTWORK_INFORMATION_REQUEST = 'ARTWORK_INFORMATION_REQUEST'
export const ARTWORK_INFORMATION_SUCCESS = 'ARTWORK_INFORMATION_SUCCESS'
export const ARTWORK_INFORMATION_FAIL = 'ARTWORK_INFORMATION_FAIL'