export const CART_ADD_ARTWORK = 'CART_ADD_ARTWORK';
export const CART_REMOVE_ARTWORK = 'CART_REMOVE_ARTWORK';
export const CART_SAVE_DELIVERY = 'CART_SAVE_DELIVERY';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT';