export const FAVORITES_LIST_REQUEST = 'FAVORITES_LIST_REQUEST';
export const FAVORITES_LIST_SUCCESS = 'FAVORITES_LIST_SUCCESS';
export const FAVORITES_LIST_FAIL = 'FAVORITES_LIST_FAIL';
export const FAVORITE_REMOVE_ITEM = 'FAVORITE_REMOVE_ITEM';
export const FAVORITE_ADD_ITEM = 'FAVORITE_ADD_ITEM'
